### PR TITLE
xboxkrnl: Fix documentation errors

### LINKED ISSUE #473: Compilation error with `-Werror -Wdocumentation` due to broken `@param` documentation comments
TIL about `-Wdocumentation`. Looks like that checks the javadoc/doxygen style comments and complains about issues.
Yes.. build-failures in comments.

There are instances where the parameter names and the comments don't match up. In a project I'm building, this causes errors because of `-Werror`.

```
In file included from nxdk/lib/windows.h:8:
In file included from nxdk/lib/winapi/windows.h:11:
In file included from nxdk/lib/winapi/memoryapi.h:5:
nxdk/lib/xboxkrnl/xboxkrnl.h:2131:11: error: parameter 'Fill' not found in the function declaration [-Werror,-Wdocumentation]
 * @param Fill The ULONG-value with which the memory block will be filled
          ^~~~
nxdk/lib/xboxkrnl/xboxkrnl.h:2131:11: note: did you mean 'Pattern'?
 * @param Fill The ULONG-value with which the memory block will be filled
          ^~~~
          Pattern
nxdk/lib/xboxkrnl/xboxkrnl.h:2303:11: error: parameter 'String1' not found in the function declaration [-Werror,-Wdocumentation]
 * @param String1 Pointer to a null-terminated single-byte string
          ^~~~~~~
nxdk/lib/xboxkrnl/xboxkrnl.h:2303:11: note: did you mean 'String'?
 * @param String1 Pointer to a null-terminated single-byte string
          ^~~~~~~
          String
nxdk/lib/xboxkrnl/xboxkrnl.h:2451:16: error: empty paragraph passed to '@param' command [-Werror,-Wdocumentation]
 * @param update
   ~~~~~~~~~~~~^
nxdk/lib/xboxkrnl/xboxkrnl.h:2610:11: error: parameter 'The' not found in the function declaration [-Werror,-Wdocumentation]
 * @param The handle of the thread object to suspend.
          ^~~
nxdk/lib/xboxkrnl/xboxkrnl.h:2610:11: note: did you mean 'ThreadHandle'?
 * @param The handle of the thread object to suspend.
          ^~~
          ThreadHandle
nxdk/lib/xboxkrnl/xboxkrnl.h:2685:11: error: parameter 'The' not found in the function declaration [-Werror,-Wdocumentation]
 * @param The handle of the thread object to resume.
          ^~~
nxdk/lib/xboxkrnl/xboxkrnl.h:2685:11: note: did you mean 'ThreadHandle'?
 * @param The handle of the thread object to resume.
          ^~~
          ThreadHandle
```

### PR DESCRIPTION
**Pull request by thrimbor**
This fixes some issues in the doxygen comments in `xboxkrnl.h`, like missing parameters names and a missing description.

Fixes #473.

### CODE REVIEW

File: lib/xboxkrnl/xboxkrnl.h [hunk 1]
```diff
@@ -2682,7 +2682,7 @@ XBAPI NTSTATUS NTAPI NtSetEvent
 
 /**
  * Resumes the target thread (see NtSuspendThread) and optionally returns the previous suspend count.
- * @param The handle of the thread object to resume.
```
Comment (JayFoxRox) [inline lib/xboxkrnl/xboxkrnl.h:2685]: nit: This one has dot at end, others don't.
Not an issue with your change, but something I first noticed here.

File: lib/xboxkrnl/xboxkrnl.h [hunk 2]
```diff
@@ -2448,7 +2448,7 @@ XBAPI NTSTATUS NTAPI PhyInitialize
 
 /**
  * Read the status information from the NICs' registers
- * @param update
+ * @param update If FALSE, the kernel returns the cached value, otherwise the hardware is polled and the cached value updated
```
Comment (JayFoxRox) [inline lib/xboxkrnl/xboxkrnl.h:2451]: nit: "returns a cached value"? It's never explained that this is cached before

Comment (thrimbor) [reply lib/xboxkrnl/xboxkrnl.h:2451]: Reworded the function description.

File: lib/xboxkrnl/xboxkrnl.h (hunk 1 above)
Comment (JayFoxRox) [reply lib/xboxkrnl/xboxkrnl.h:2685]: Just checking @thrimbor, because you pushed but didn't do this: Will this remain as-is?

Eitherway: I reviewed and tested locally. Feel free to self-merge at your discretion. If not merged already I'll probably merge it later today.

Comment (thrimbor) [reply lib/xboxkrnl/xboxkrnl.h:2685]: We seem to have a mix of the comments ending with a dot and those who don't - if we decide that one of those styles is preferred, I think it's best to change them in a separate commit/PR.
