### PR TITLE
samples: Do not restart

### LINKED ISSUE #45: Remove reboot on triangle and mesh samples
I added it for convenience (so I wouldn't have to reach over and restart my Xbox), but most people seem to perceive it as a crash since they haven't read the source code--so it should probably just be removed.

### PR DESCRIPTION
**Pull request by dracc**
Closes #45.

Small fix to make sure the samples doesn't automatically restart.

### CODE REVIEW

File: samples/mesh/main.c [hunk 1]
```diff
@@ -265,17 +261,7 @@ void main(void)
...
             last = now;
         }
-
-        /* Exit the demo after timeout */
-        if ((reboot_after > 0) && ((now-start) > reboot_after)) {
-            break;
-        }
     }
-
-    MmFreeContiguousMemory(alloc_vertices);
```
Comment (mborgerson) [inline samples/mesh/main.c]: May want to keep these even if they are unreachable so people know what cleanup would look like.

Comment (JayFoxRox) [reply samples/mesh/main.c]: Agree. keep this and `pb_kill`.
Then add a comment to tell people that this is not reachable before the cleanup code.

**Comment by JayFoxRox** [comment]
Thanks!
