### PR TITLE
lwip C++ compat fixes

### LINKED ISSUE #296: lwip doesn't work with C++ projects
I'm guessing it's due to the fact that the `-I` flags only get added to `CFLAGS` and thus the files aren't found by the C++ compiler.

### PR DESCRIPTION
**Pull request by thrimbor**
This fixes some issues that occur when using lwip from C++, such as missing include paths, name mangling, and issues with including `errno.h.` (which was encountered by @dracc).

Mostly tested by building one of the http server samples as C++ code, and @dracc's ftpserver-branch of NevolutionX.

Closes #296.

### CODE REVIEW

File: lib/net/pktdrv/pktdrv.h [hunk 1]
```diff
@@ -1,6 +1,10 @@
 #ifndef _Pktdrv_
 #define _Pktdrv_
 
+#ifdef __cplusplus
+extern "C" {
+#endif
```
Comment (JayFoxRox) [inline lib/net/pktdrv/pktdrv.h]: I wonder if we should even C++-ify all of our headers.
If it's well defined that certain APIs are C APIs, then I don't see the issue with doing it like this instead:

```c
// (in app.cpp)

#include <windows.h>

extern "C" {
#include "foo.h"
}
```

File: lib/net/nforceif/include/lwipopts.h [hunk 2]
```diff
@@ -437,7 +437,13 @@
 #define TCP_QLEN_DEBUG   LWIP_DBG_ON
 #define TCP_RST_DEBUG    LWIP_DBG_ON
 
+#ifdef __cplusplus
+extern "C" {
+#endif
 extern unsigned char debug_flags;
+#ifdef __cplusplus
+}
+#endif
```
Comment (JayFoxRox) [inline lib/net/nforceif/include/lwipopts.h]: Wouldn't this file only be included by C code in lwip? When would this ever be compiled by a C++ compiler?

Comment (thrimbor) [reply lib/net/nforceif/include/lwipopts.h]: It gets pulled in indirectly by lwip headers.

File: lib/net/pktdrv/pktdrv.h (hunk 1 above)
Comment (thrimbor) [reply lib/net/pktdrv/pktdrv.h]: I think we should - people usually expect C headers to just work in C++, even though the languages are quite different internally, and I consider it to be much cleaner to adjust the header once.

File: lib/net/nforceif/include/lwipopts.h (hunk 2 above)
Comment (JayFoxRox) [reply lib/net/nforceif/include/lwipopts.h]: I see. lwip seems to have this C++ handling in each header *after* `#include` lines.
Resolved.

File: lib/net/Makefile [hunk 3]
```diff
@@ -18,3 +18,6 @@ SRCS += $(LWIPSRCS) $(DRIVERSRCS)
 CFLAGS += -I $(LWIPDIR)/include
 CFLAGS += -I $(NXDK_DIR)/lib/net/nforceif/include
 CFLAGS += -I $(NXDK_DIR)/lib/net/pktdrv
+CXXFLAGS += -I $(LWIPDIR)/include
```
Comment (mborgerson) [inline lib/net/Makefile]: Ideally we'd just have one `INCLUDES` variable that is included for both C and C++ definitions. Don't have to fix this now, but thought for the future
