### PR TITLE
samples: Remove pb_* from samples not using pbkit

### LINKED ISSUE #90: Samples pb_init() is ugly
Most samples do a switch case for pb_init() similar to
```c
switch(pb_init()) {
  case 0: break;
  default:
    XSleep(2000);
    XReboot();
    return -1;
}
```

This is not pleasing on the eyes.
@JayFoxRox suggested a more standard
```c
int ret = pb_init();
if (ret != 0) {
  XSleep(2000);
  XReboot();
  return -1;
}
```
which looks nicer IMO. This is also the way most other libs I've worked with suggests initialization checking to be done.

### LINKED ISSUE #212: Samples initialize pbkit, even though they never use it
Some samples intialize pbkit, but continue with software rendering.
I guess the intention is to call `pb_show_debug_screen` - but that shouldn't be necessary.
pbkit doesn't even own that framebuffer..

Currently, the framebuffer is owned by nobody, but should probably be (optionally) claimable by XVideo (See #169).
XVideo is responsible for setting up the display mode and the framebuffer address used for output.

Who owns the framebuffer depends on who draws to it:
* Allocation for CPU rendering should probably be done in XVideo (reclaim the buffer used on application entry) or the application (creating a new buffer).
* Allocation for GPU rendering should probably be done in an abstraction layer over pbkit (important for features like render-to-texture).

So, pbkit should only be used if the GPU is required (for drawing or computations).
pbkit shouldn't own any framebuffer (at very least none that it doesn't use itself) - it should only own optimization structures (DMA descriptors / compression tables / ...).

---

I noticed this problem because `pb_init` fails if the framebuffer isn't 32-bit.
It also increases RAM usage because of GPU framebuffers (which pbkit currently owns, even though it probably shouldn't) and helper structures.
Not having to deal with pbkit would also simplify code which only uses CPU rendering.

However, there's one exception why we might still need pbkit (or a minimal GPU driver):
I'm not sure if it can happen, but maybe the GPU can be left in a bad state when switching applications. That could have side-effects in RAM. To avoid that, we'd have to stop the GPU at startup. Currently, `pb_init` takes care of such things.
Someone should construct a test to see if this is an issue.

### PR DESCRIPTION
**Pull request by dracc**
Closes #212

Edit: Closes #90

Edit2: Copied from 212:
**H**owever, there's one exception why we might still need pbkit (or a minimal GPU driver):
I'm not sure if it can happen, but maybe the GPU can be left in a bad state when switching applications. That could have side-effects in RAM. To avoid that, we'd have to stop the GPU at startup. Currently, pb_init takes care of such things.
Someone should construct a test to see if this is an issue.

### CODE REVIEW

File: samples/sdl/main.c [hunk 1]
```diff
@@ -290,7 +287,7 @@ void demo(void)
         SDL_WINDOW_SHOWN);
     if(window == NULL)
     {
-        debugPrint( "Window could not be created!\n");
+        debugPrint("Window could not be created!\n");
```
Comment (dracc) [inline samples/sdl/main.c]: Unintended change. Will let it stay as the extra whitespace was probably unintentional.

**Comment by mborgerson** [comment]
Thanks
